#finding a splices motif
seq1 = 'TGAGTACGAGACCTTTCTTCCTGTTGTCGGCCCCCAGTTGGCGTTGGTTCCGCTAAGAAGCGAGGAAGGAGAAGTGTCGCTTGGATGTGGGCTGCGCGCCCGACTTATTGCGGATTCCTGGTCCTAAAATCTTTCTCTCAGTGCGACAGGGTAGTCGCCTCATATTTAAGGTAACTACCGTTGTCTCATGACGTCTTTCGGGCAGGTTCGGTCTTTAACAGAGCGTCGACGGTTTGAATTCGAATGTATTGAATATAAGTGGTCAAACCGAACGCTTAGCCGATACGACTATCCCCATATTGGGGACCTCCAGAAACCCATCGGGCGTATCACGGGCCGGGAAAACGGGTATAGCACATTGGAGATTACTAGGAACAGGCCTACGGGTGCGAGTTGCTAAACAGAGGCTACTCTTACACTGCGGTCGCCACCGTCGCGCTCGTAACCTAAATTAGACGACTATAGTTTCCCAAAAGGGTCGCCCCTCCAGAATCCCCGAGAGATCGCATCTAGCCTGGCGGAGTCGATTATCAGATGTCTAGACTGCTCCCTCTACAGGTAATCGGCAGGCCATAACAGCTCTTATTAATGTCAGAAATACGTGCCCTGACAACCTCATACTAATAACAAGGTCACACCATCCCCTCCCCGAGGGGGGACTGGCGCACTACGATCAGCAGTCGATCCGAAATGTTGTTCGCAGATAACAAACCCTAACGCCTAGTCCCTTTATATTTTTTTAAAACTCTTCACCTTGCTCTGAGCCCTGTCACCAGCCTGGACTAAGATTGCATTTACTTCCTGACCGTTCAATCCATATAGGAATCATAAGCGTACTCGCGCTATGTG'
seq2 = 'AGGGGCGGGTCCCGTTTGCTGGTGACATGGTACGACTTCGGATGCACAATTCGATCGTCGATGTTCTGCTTACTGCTCATT'
pos = 0
lastpos= 0 
substrpos=""

for i in seq2:
    for j in seq1:
        pos += 1
        if i ==j:
            if pos > lastpos:
                lastpos = pos
                substrpos += (str(lastpos)+ " ")
                pos=0
                break

print (substrpos)